/*
 * Runs after the Better Auth CLI (`pnpm auth:generate`) to apply our conventions (PRODUCT.md §7.11, §8):
 * - IDs are UUIDv7 generated by the app (auth.ts generateId), stored in `uuid` columns, so tenant
 *   tables can reference `organization.id` with matching types. `account.account_id` stays text:
 *   it holds external provider account IDs.
 * - Every timestamp is `timestamptz` (UTC).
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const UUID_COLUMNS = ["id", "user_id", "organization_id", "inviter_id", "active_organization_id"];
const HEADER = `/*
 * Better Auth tables, owned by infra/auth (PRODUCT.md §7.4, §8). GENERATED: do not edit by hand.
 * Regenerate with \`pnpm --filter @app/api auth:generate\`, then \`db:generate\` for the migration.
 */
`;

export function postprocessAuthSchema(source: string): string {
  let out = source;
  for (const column of UUID_COLUMNS) {
    out = out.replaceAll(`text("${column}")`, `uuid("${column}")`);
  }
  out = out.replace(/timestamp\("([a-z_]+)"\)/g, 'timestamp("$1", { withTimezone: true })');
  out = out.replace(/import \{([^}]*)\} from "drizzle-orm\/pg-core";/, (_match, names: string) => {
    const set = new Set(
      names
        .split(",")
        .map((n) => n.trim())
        .filter(Boolean),
    );
    set.add("uuid");
    return `import { ${[...set].sort().join(", ")} } from "drizzle-orm/pg-core";`;
  });
  return out.startsWith(HEADER) ? out : `${HEADER}${out}`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const file = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../src/infra/auth/schema.ts",
  );
  writeFileSync(file, postprocessAuthSchema(readFileSync(file, "utf8")));
  process.stdout.write(`post-processed ${path.relative(process.cwd(), file)}\n`);
}
