/*
 * P0-T09 AC: a module generated by `pnpm new:module` passes lint, typecheck and `pnpm arch`.
 * Runs the generator on a scratch copy of backend/src (never the real tree), then the real tools.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { generateModule } from "../../../scripts/new-module.js";
import { checkArchitecture } from "../../../../scripts/arch-check.mjs";

const BACKEND = fileURLToPath(new URL("../../../", import.meta.url));
const REPO = path.resolve(BACKEND, "..");
const SCRATCH = path.join(BACKEND, ".arch-selftest", `gen-${randomBytes(4).toString("hex")}`);
const COPY = path.join(SCRATCH, "backend");

const require = createRequire(import.meta.url);

/* Resolves a package's bin script so it runs through node directly (no shell, safe with spaces in paths). */
function binOf(pkg: string, bin: string): string {
  const manifest = require.resolve(`${pkg}/package.json`, { paths: [REPO] });
  return path.join(path.dirname(manifest), bin);
}

function run(script: string, args: string[], cwd: string) {
  const result = spawnSync(process.execPath, [script, ...args], { cwd, encoding: "utf8" });
  return { status: result.status, output: `${result.stdout}${result.stderr}` };
}

beforeAll(() => {
  mkdirSync(COPY, { recursive: true });
  cpSync(path.join(BACKEND, "src"), path.join(COPY, "src"), {
    recursive: true,
    filter: (src) => !src.includes(`${path.sep}__tests__`),
  });
  cpSync(path.join(REPO, "tsconfig.base.json"), path.join(SCRATCH, "tsconfig.base.json"));
  const tsconfig = JSON.parse(readFileSync(path.join(BACKEND, "tsconfig.json"), "utf8")) as Record<
    string,
    unknown
  >;
  writeFileSync(
    path.join(COPY, "tsconfig.json"),
    JSON.stringify({
      ...tsconfig,
      extends: "../tsconfig.base.json",
      compilerOptions: { rootDir: "src", noEmit: true },
    }),
  );
});

afterAll(() => {
  rmSync(SCRATCH, { recursive: true, force: true });
});

describe("pnpm new:module", () => {
  it("generates a module that passes typecheck, lint and the architecture rules", async () => {
    const files = generateModule({ name: "sample-thing", root: COPY, calls: ["audit"] });
    expect(files).toContain(path.join("src", "modules", "sample-thing", "index.ts"));
    expect(existsSync(path.join(COPY, "src/modules/sample-thing/jobs/index.ts"))).toBe(true);
    expect(readFileSync(path.join(COPY, "src/composition/modules.ts"), "utf8")).toContain(
      "createSampleThingModule({ infra })",
    );
    const edges = JSON.parse(
      readFileSync(path.join(COPY, "src/composition/module-edges.json"), "utf8"),
    );
    expect(edges.modules["sample-thing"]).toEqual(["audit"]);

    const tsc = run(
      binOf("typescript", "bin/tsc"),
      ["-p", path.join(COPY, "tsconfig.json")],
      BACKEND,
    );
    expect(tsc.output).toBe("");
    expect(tsc.status).toBe(0);

    const lint = run(
      binOf("eslint", "bin/eslint.js"),
      ["--no-warn-ignored", path.join(COPY, "src/modules/sample-thing")],
      REPO,
    );
    expect(lint.output.trim()).toBe("");
    expect(lint.status).toBe(0);

    const { violations } = await checkArchitecture({
      baseDir: SCRATCH,
      projects: [{ files: ["backend/src"], tsConfig: "backend/tsconfig.json" }],
    });
    expect(violations.map((v) => `${v.rule.name}: ${v.from} -> ${v.to}`)).toEqual([]);
  }, 180_000);

  it("refuses bad names and existing modules", () => {
    expect(() => generateModule({ name: "Bad_Name", root: COPY })).toThrow(/kebab-case/);
    expect(() => generateModule({ name: "sample-thing", root: COPY })).toThrow(/already exists/);
    expect(() => generateModule({ name: "other", root: COPY, calls: ["nope"] })).toThrow(
      /unknown module/,
    );
  });
});
