/* Public entry for @app/shared: Zod schemas, types, constants and pure functions only (PRODUCT.md §7.1 rule 10). */
export { PRODUCT_NAME, MONITOR_STATUSES, type MonitorStatus } from "./constants/product.js";
export { API_ERROR_CODES, type ApiErrorCode } from "./constants/api-errors.js";
export {
  LAUNCH_REGIONS,
  REGIONS,
  SEVERITIES,
  type Region,
  type Severity,
} from "./constants/regions.js";
export {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  WORKSPACE_ROLES,
  WORKSPACE_STATEMENTS,
  broadestRole,
  isWorkspaceRole,
  roleCan,
  roleStatements,
  type Permission,
  type RoleStatements,
  type WorkspaceResource,
  type WorkspaceRole,
} from "./constants/roles.js";
export {
  CONTACT_METHOD_TYPES,
  DEFAULT_RULE_DELAYS,
  MAX_CONTACT_METHODS,
  MAX_RULES_PER_URGENCY,
  MAX_RULE_DELAY_MINUTES,
  URGENCIES,
  contactCodeSchema,
  createContactMethodSchema,
  notificationRuleSchema,
  planFanOut,
  replaceRulesSchema,
  urgencyOf,
  type ContactMethodType,
  type ContactMethodView,
  type CreateContactMethodInput,
  type FanOutMethod,
  type FanOutStep,
  type NotificationRuleInput,
  type NotificationRuleView,
  type NotificationRulesView,
  type Urgency,
} from "./schemas/contacts.js";
export {
  ESCALATION_TARGET_TYPES,
  MAX_ESCALATION_REPEATS,
  MAX_ESCALATION_STEPS,
  MAX_LAYERS,
  MAX_PARTICIPANTS,
  MAX_STEP_DELAY_MINUTES,
  MAX_STEP_TARGETS,
  createEscalationPolicySchema,
  escalationStepSchema,
  escalationTargetSchema,
  updateEscalationPolicySchema,
  type CreateEscalationPolicyInput,
  type EscalationPolicyView,
  type EscalationStep,
  type EscalationTarget,
  type EscalationTargetType,
  type EscalationTargetView,
  type IncidentEscalationView,
  type UpdateEscalationPolicyInput,
  MAX_RESTRICTIONS,
  MAX_TIMELINE_DAYS,
  ROTATIONS,
  createOverrideSchema,
  createScheduleSchema,
  restrictionSchema,
  scheduleLayerSchema,
  updateScheduleSchema,
  type CreateOverrideInput,
  type CreateScheduleInput,
  type OnCallNow,
  type OnCallPerson,
  type OnCallSegment,
  type Restriction,
  type Rotation,
  type ScheduleLayerInput,
  type ScheduleLayerView,
  type ScheduleOverrideView,
  type ScheduleSummary,
  type ScheduleView,
  type UpdateScheduleInput,
} from "./schemas/oncall.js";
export {
  CHECK_ERRORS,
  CHECK_ERROR_CODES,
  checkErrorImpact,
  countsAsCustomerFailure,
  type CheckErrorCode,
  type CheckErrorImpact,
} from "./constants/check-errors.js";
export {
  BILLING_INTERVALS,
  CANCEL_REASONS,
  CREDIT_PACKS,
  PLAN_FEATURES,
  PLAN_KEYS,
  SUBSCRIPTION_STATUSES,
  type BillingInterval,
  type BillingState,
  type CancelReason,
  type CatalogPlan,
  type CheckoutSession,
  type CreditBucket,
  type CreditLedgerEntry,
  type CreditPack,
  type CreditsState,
  type Entitlements,
  type MonitorUsage,
  type PaidPlanKey,
  type PlanFeature,
  type PlanFeatures,
  type PlanKey,
  type PlanLimits,
  type PlanSource,
  type SubscriptionStatus,
  type SubscriptionView,
  type Unlimited,
  type UsageMeter,
} from "./schemas/billing.js";
export { monitorStatusSchema } from "./schemas/monitor-status.js";
export { problemSchema, type Problem } from "./schemas/problem.js";
export {
  EVENT_SCHEMAS,
  EVENT_TYPES,
  isEventType,
  type EventPayload,
  type EventType,
} from "./schemas/events.js";
export {
  DNS_RECORD_TYPES,
  JSON_QUERY_OPERATORS,
  MONITOR_TYPES,
  PROBE_MONITOR_TYPES,
  createMonitorSchema,
  dnsConfigSchema,
  domainConfigSchema,
  effectiveRecoverySuccesses,
  heartbeatConfigSchema,
  heartbeatScheduleSchema,
  httpConfigSchema,
  isAcceptedStatus,
  jsonQueryConfigSchema,
  keywordConfigSchema,
  monitorConfigSchema,
  monitorSettingsObject,
  monitorSettingsSchema,
  pingConfigSchema,
  sslConfigSchema,
  tcpConfigSchema,
  websocketConfigSchema,
  type CreateMonitorInput,
  type MonitorConfig,
  type MonitorConfigInput,
  type MonitorSettings,
  type MonitorType,
} from "./schemas/monitors.js";
export {
  checkResultSchema,
  timingsSchema,
  tlsInfoSchema,
  type CheckResult,
} from "./schemas/results.js";
export {
  EVIDENCE_BODY_MAX_CHARS,
  EVIDENCE_HEADERS,
  EVIDENCE_HEADER_VALUE_MAX,
  checkEvidenceSchema,
  pickEvidenceHeaders,
  type CheckEvidence,
} from "./schemas/evidence.js";
export {
  evidenceBundleSchema,
  evidenceKey,
  evidenceKeyPrefix,
  evidenceRefSchema,
  type EvidenceBundle,
  type EvidenceRef,
  type IncidentEvidenceItem,
} from "./schemas/evidence-bundle.js";
export {
  TIMING_PHASES,
  describeEvidenceTiming,
  describeTiming,
  formatMs,
  slowestPhase,
  type PhaseTimings,
  type TimingPhase,
} from "./explain/timing.js";
export {
  PROBE_API_PREFIX,
  PROBE_CAPABILITIES,
  PROBE_HEADERS,
  PROBE_MAX_BATCH_RESULTS,
  PROBE_MAX_CLOCK_SKEW_SECONDS,
  assignedMonitorSchema,
  assignmentsQuerySchema,
  assignmentsResponseSchema,
  helloRequestSchema,
  helloResponseSchema,
  probeHeartbeatSchema,
  probeSigningString,
  probeTaskSchema,
  resultsAcceptedSchema,
  resultsBatchSchema,
  tasksQuerySchema,
  tasksResponseSchema,
  type AssignedMonitor,
  type AssignmentsResponse,
  type HelloRequest,
  type HelloResponse,
  type ProbeHeartbeat,
  type ProbeTask,
  type ResultsBatch,
} from "./schemas/probe-protocol.js";
export { JSON_SCHEMA_EXPORTS } from "./schemas/json-schema-exports.js";
export {
  ALERT_EVENT_KINDS,
  CHANNEL_STATUSES,
  CHANNEL_TYPES,
  alertPolicyBodySchema,
  alertPolicyRulesSchema,
  STATE_SYNC_EVENTS,
  channelAccepts,
  channelRulesPatchSchema,
  channelRulesSchema,
  mergeChannelRules,
  TEAMS_WORKFLOW_HOST_SUFFIXES,
  createChannelSchema,
  discordChannelConfigSchema,
  emailChannelConfigSchema,
  slackChannelConfigSchema,
  teamsChannelConfigSchema,
  telegramChannelConfigSchema,
  updateChannelSchema,
  webhookChannelConfigSchema,
  type DiscordChannelConfig,
  type SlackChannelConfig,
  type TeamsChannelConfig,
  type TelegramChannelConfig,
  type WebhookChannelConfig,
  type AlertEventKind,
  type AlertPolicyInput,
  type AlertPolicyRules,
  type ChannelRules,
  type ChannelRulesPatch,
  type ChannelStatus,
  type ChannelType,
  type CreateChannelInput,
  type EmailChannelConfig,
} from "./schemas/alerting.js";
export {
  NTFY_DEFAULT_SERVER,
  OPSGENIE_REGIONS,
  PUSHOVER_CRITICAL_MODES,
  SECRET_MASK,
  SERVICE_REGIONS,
  googleChatChannelConfigSchema,
  phoneChannelConfigSchema,
  phoneConfirmationSchema,
  phoneNumberSchema,
  phoneVerificationSchema,
  gotifyChannelConfigSchema,
  matrixChannelConfigSchema,
  mattermostChannelConfigSchema,
  ntfyChannelConfigSchema,
  opsgenieChannelConfigSchema,
  pagerDutyChannelConfigSchema,
  pushbulletChannelConfigSchema,
  pushoverChannelConfigSchema,
  rocketChatChannelConfigSchema,
  slackWebhookChannelConfigSchema,
  splunkOnCallChannelConfigSchema,
  webhookHeadersSchema,
  zulipChannelConfigSchema,
  type GoogleChatChannelConfig,
  type PhoneChannelConfig,
  type PhoneCost,
  type GotifyChannelConfig,
  type MatrixChannelConfig,
  type MattermostChannelConfig,
  type NtfyChannelConfig,
  type OpsgenieChannelConfig,
  type OpsgenieRegion,
  type PagerDutyChannelConfig,
  type PushbulletChannelConfig,
  type PushoverChannelConfig,
  type RocketChatChannelConfig,
  type ServiceRegion,
  type SlackWebhookChannelConfig,
  type SplunkOnCallChannelConfig,
  type WebhookHeaders,
  type ZulipChannelConfig,
} from "./schemas/channel-configs.js";
export {
  CHANNEL_CAPABILITIES,
  CHANNEL_FIELDS,
  CHANNEL_LABELS,
  INTEGRATIONS,
  INTEGRATION_CATEGORIES,
  INTEGRATION_IDS,
  findIntegration,
  integrationFields,
  integrationForChannel,
  type ChannelCapabilities,
  type ChannelField,
  type ChannelFieldKind,
  type FollowUpStyle,
  type IntegrationCategory,
  type IntegrationDefinition,
  type IntegrationId,
} from "./integrations/catalog.js";
export { createAddressPolicy, embeddedIPv4, type AddressPolicy } from "./net/address-policy.js";
export {
  cronProblem,
  nextExpectedAt,
  type HeartbeatSchedule,
} from "./schemas/heartbeat-schedule.js";
export {
  explainFailure,
  type Explanation,
  type FailureCategory,
  type FailureFacts,
} from "./explain/failure.js";
export {
  noiseLevel,
  suggestTuning,
  type NoiseStats,
  type TuningSettings,
  type TuningSuggestion,
} from "./explain/tuning.js";
export {
  MAINTENANCE_MAX_DAYS,
  MAINTENANCE_MAX_MONITORS,
  createMaintenanceWindowSchema,
  maintenanceScopeSchema,
  updateMaintenanceWindowSchema,
  type CreateMaintenanceWindowInput,
  type MaintenanceScope,
  type MaintenanceWindowView,
  type UpdateMaintenanceWindowInput,
} from "./schemas/maintenance.js";
