/*
 * Bundles the sync tool into one file, action/index.mjs, which is committed: a GitHub Action runs
 * from the repository as it is, with no install step. A test fails when the file is out of date.
 */
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = (path) => fileURLToPath(new URL(path, import.meta.url));

export const BUNDLE = here("./action/index.mjs");

export const bundleOptions = {
  entryPoints: [here("./src/main.ts")],
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  legalComments: "none",
  /*
   * The YAML library is CommonJS and asks for Node's built-ins with require(), which an ES module
   * doesn't have; the banner gives the bundle one.
   */
  banner: {
    js: [
      "#!/usr/bin/env node",
      "/* Generated by tools/sync/build.mjs from tools/sync/src. Do not edit. */",
      'import { createRequire as __createRequire } from "node:module";',
      "const require = __createRequire(import.meta.url);",
    ].join("\n"),
  },
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await build({ ...bundleOptions, outfile: BUNDLE });
}
